# we use rest client VS code extension for testing
# which is quite basic 
# since it is my first time testing an API
# use '###' to separate a request from others
# click on 'send request' on top of every request to send it
# Installation steps provided in documentation
# we must give a space between 'Content-Type' and the json payload

### For creating a new match
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// click on send request
POST http://localhost:3000/matches
Content-Type: application/json

{
    "team1_Name" : "Chennai Super Kings",
    "team2_Name" : "Mumbai Indians",
    "team1_Composition" : ["M.S. Dhoni","Ravidarsinh Jadeja", "Suresh Raina","Tushar Deshpande","Devon Conway"],
    "team2_Composition" : ["Rohit Sharma", "Dewald Brevis", "Suryakumar Yadav", "Ishan Kishan" , "N. Tilak Varma"],
    "match_date" : "16-06-2001",
    //I am using DD-MM-YYYY format in string format
    //It should be maintained through out the project
    "venue": "Mumbai",
    "palyer_of_the_match": "Not declared yet",
    "winning_team": "Not declared yet",
    "losing_team":"Not declared yet"
}
// we must give a space between the Content-type and json payload

###(we use '###' to separate requests)

// adding another match
//click on send request

POST http://localhost:3000/matches
Content-Type: application/json

{
    "team1_Name" : "KingsXI Punjab",
    "team2_Name" : "Rajasthan Royals",
    "team1_Composition" : ["Shikhar. Dhawan","Atharva. Taide","Bhanuka. Rajapaksa","Harpreet. Singh","Shahrukh. Khan"],
    "team2_Composition" : ["Sanju Samson","Devdutt Padikkal","Jos Buttler","Shimron Hetmyer","Yashasvi Jaiswal"],
    "match_date" : "16-06-2001",
    "venue": "Mohali",
    "palyer_of_the_match": "Not declared yet",
    "winning_team": "Not declared yet",
    "losing_team":"Not declared yet"
}
###
// adding another match of a different date

POST http://localhost:3000/matches
Content-Type: application/json

{
    "team1_Name" : "Royal Challengers Bangalore",
    "team2_Name" : "Lucknow Super Giants",
    "team1_Composition" : ["Faf du Plessis", "Akash Deep", "Anuj Rawat", "Avinash Singh", "David Willey"],
    "team2_Composition" : ["Avesh Khan",  "Mark Wood",  "Mayank Yadav", "Mohsin Khan", "Ravi Bishno"],
    "match_date" : "17-06-2001",
    "venue": "Lucknow",
    "palyer_of_the_match": "Not declared yet",
    "winning_team": "Not declared yet",
    "losing_team":"Not declared yet"
}

###
// checking the validation error handeling by removing one of the required fields
//click on 'send request' to get the error in response
POST http://localhost:3000/matches
Content-Type: application/json

{
    "team1_Name" : "Royal Challengers Bangalore",
    "team2_Name" : "Lucknow Super Giants",
    "team1_Composition" : ["Faf du Plessis", "Akash Deep", "Anuj Rawat", "Avinash Singh", "David Willey"],
    "team2_Composition" : ["Avesh Khan",  "Mark Wood",  "Mayank Yadav", "Mohsin Khan", "Ravi Bishno"],
    "match_date" : "",
    "venue": "Lucknow",
    "palyer_of_the_match": "Not declared yet",
    "winning_team": "Not declared yet",
    "losing_team":"Not declared yet"
}
###
// you can add your own tests by copying the above fromat



// creating a match tests ended
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////



// getting all matches by date
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// we are using query strings to get matches by date

GET http://localhost:3000/matches?match_date=16-06-2001

###
// creating another query strings

GET  http://localhost:3000/matches?match_date=17-06-2001

###
// using a date that is not inside the collection
 
GET http://localhost:3000/matches?match_date=18-06-2001

### 
// using a date with wrong format

GET http://localhost:3000/matches?match_date=2001-06-16

### 
// you can make your own test cases by following the above format and adding more matches as you please


//getting matches by date tests ended
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



